imu_topic: /livox/imu_fixed
lidar_topic: /scan_points_fixed
body_frame: base_link
world_frame: map
print_time_cost: false

lidar_type: 1   # 0 = Livox CustomMsg, 1 = PointCloud2

lidar_filter_num: 6
lidar_min_range: 0.5
lidar_max_range: 70.0
scan_resolution: 0.2
map_resolution: 0.2

cube_len: 300
det_range: 40
move_thresh: 1.5

na: 0.1
ng: 0.1
nba: 0.0001
nbg: 0.0001

imu_init_num: 200
near_search_num: 5
ieskf_max_iter: 5

gravity_align: true
esti_il: false

r_il: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
t_il: [-0.011, -0.02329, 0.04412]

lidar_cov_inv: 1000.0
