#!/bin/sh
#
# @name Gazebo x500 lidar front
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=marvin_drohne_alles}

. ${R}etc/init.d-posix/airframes/40011_gz_marvin_drohne

param set-default EKF2_EV_CTRL 3
param set-default EKF2_HGT_REF 3
param set-default EKF2_BARO_CTRL 0
param set-default EKF2_MAG_TYPE 0

param set-default EKF2_GPS_CTRL 0
param set-default GPS_1_CONFIG 0

