#!/bin/sh
#
# @name Gazebo x500
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=marvin_drohne}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.23
param set-default CA_ROTOR0_PY 0.23
param set-default CA_ROTOR0_PZ 0.05
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.23
param set-default CA_ROTOR1_PY -0.23
param set-default CA_ROTOR1_PZ 0.05
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.23
param set-default CA_ROTOR2_PZ 0.05
param set-default CA_ROTOR2_KM -0.23

param set-default CA_ROTOR3_PX -0.23
param set-default CA_ROTOR3_PY 0.23
param set-default CA_ROTOR3_PZ 0.05
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1500
param set-default SIM_GZ_EC_MAX2 1500
param set-default SIM_GZ_EC_MAX3 1500
param set-default SIM_GZ_EC_MAX4 1500

param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 2


# Indoor-Flugverhalten (PX4-Defaults sind Outdoor: 12 m/s, 45° Neigung, 200°/s Yaw).
# Offboard-Positions-Setpoints laufen ohne Trajektorien-Glaettung direkt in den
# Positionsregler -> nur Geschwindigkeits-/Neigungs-/Yawraten-Limits bremsen.
# Ruhige Manoever schonen auch FAST-LIO (Bewegungsunschaerfe, IMU-Spitzen).
param set-default MPC_XY_VEL_MAX 1.5
param set-default MPC_XY_CRUISE 1.0
param set-default MPC_Z_VEL_MAX_UP 1.0
param set-default MPC_Z_VEL_MAX_DN 0.7
param set-default MPC_TILTMAX_AIR 20
param set-default MPC_ACC_HOR 1.5
param set-default MPC_ACC_HOR_MAX 2.0
param set-default MPC_YAWRAUTO_MAX 30
param set-default MC_YAWRATE_MAX 60
